name: intl_helper
description: A tool for use intl_translate package easily.
version: 0.1.0
#homepage: https://github.com/hefemk/intl_helper
#author: HEFE <hefe.mk@gmail.com>

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  path: ^1.4.1
  args: "^0.13.7"

#dev_dependencies:
#  test: ^0.12.0
